PetFoodCalculator/urls.py
from django.contrib import admin
from django.urls import path, include

from PetFoodCalculator import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("calculator.urls", namespace="calculator")),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

calculator/urls.py
from django.urls import path
from calculator import views

app_name = "calculator"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("pet/create/", views.PetCreateView.as_view(), name="pet_create"),
    path("pet/<uuid:pk>/", views.PetDetailView.as_view(), name="pet_detail"),
    path("pet/<uuid:pk>/update/", views.PetUpdateView.as_view(), name="pet_update"),
    path("pet/<uuid:pk>/delete/", views.PetDeleteView.as_view(), name="pet_delete"),
    path("pet/<uuid:pk>/calculate_price/", views.PetCalculatePrice.as_view(), name="calculate_price"),
    path("food/create/", views.FoodCreateView.as_view(), name="food_create"),
    path("food/<int:pk>/update/", views.FoodUpdateView.as_view(), name="food_update"),
    path("food/<int:pk>/delete/", views.FoodDeleteView.as_view(), name="food_delete"),
]

users/urls.py
from django.urls import path

from .views import (
    UserDetailView,
    UserSettingsView, UserDeleteView, BuyMeCoffeeView, SendMessageView,
)

app_name = "users"

urlpatterns = [
    path("me/", UserDetailView.as_view(), name="user-detail"),
    path("me/settings/", UserSettingsView.as_view(), name="user-settings"),
    path("me/delete/", UserDeleteView.as_view(), name="user-delete"),
    path("bymeacoffee/", BuyMeCoffeeView.as_view(), name="by-me-a-coffee"),
    path("send-message", SendMessageView.as_view(), name="send-message"),
]

calculator/models.py
import uuid
from decimal import Decimal

from django.db import models

from users.models import User


class Pet(models.Model):
    CALCULATE_PRICE_CHOICES = [
        ("on", "On"),
        ("off", "Off"),
    ]

    PET_ICON_CHOICES = [
        ("cat_icon.png", "Cat"),
        ("dog_icon.png", "Dog"),
        # ("bird", "Bird"),
        # ("hamster", "Hamster"),
        # ("rabbit", "Rabbit"),
        # ("turtle", "Turtle"),
        # ("snake", "Snake"),
        # ("lizard", "Lizard"),
        # ("frog", "Frog"),
        # ("hedgehog", "Hedgehog"),
        # ("guinea_pig", "Guinea Pig"),
        # ("chinchilla", "Chinchilla"),
        ("other_icon.png", "Other"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=30)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="pets")
    is_default = models.BooleanField(default=False)
    calculate_price = models.CharField(max_length=3, choices=CALCULATE_PRICE_CHOICES, default="off")
    pet_icon = models.CharField(max_length=30, choices=PET_ICON_CHOICES, default="other_icon.png")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["owner", "name"], name="unique_pet_per_owner"
            )
        ]
        ordering = ["created_at"]


class Food(models.Model):
    name = models.CharField(max_length=20, blank=True, null=True)
    kcal = models.PositiveIntegerField(blank=True, null=True)
    meals = models.PositiveIntegerField(blank=True, null=True)
    meal_size = models.PositiveIntegerField(blank=True, null=True)

    package_size = models.PositiveIntegerField(blank=True, null=True)
    package_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, related_name="foods")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["id"]

    @property
    def kcal_per_day(self):
        if None in (self.kcal, self.meals, self.meal_size):
            return 0
        if 0 in (self.kcal, self.meals, self.meal_size):
            return 0

        return round((self.kcal / 1000) * self.meal_size * self.meals, 2)


    @property
    def cost_per_day(self):
        if None in (self.kcal, self.meals, self.meal_size, self.package_size, self.package_price):
            return Decimal(0.00)
        if 0 in (self.kcal, self.meals, self.meal_size, self.package_size, self.package_price):
            return Decimal(0.00)

        return round(
            (self.package_price / self.package_size) * self.meal_size * self.meals,
            2,
        )

calculator/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import UpdateView, DetailView, DeleteView

from calculator.models import Pet, Food


class HomeView(View):
    def get(self, request, *args, **kwargs):
        current_user = request.user

        if not current_user.is_authenticated:
            return render(request, "calculator/home_guest.html")

        pets = Pet.objects.filter(owner=current_user)
        pet = (
            pets.filter(is_default=True).first() or pets.order_by("created_at").first()
        )
        if pet:
            return redirect("calculator:pet_detail", pk=pet.id)

        return render(request, "calculator/home.html")


class PetCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user = request.user
        pet_name = request.POST.get("pet_name")
        is_default = request.POST.get("is_default") == "on"

        if is_default:
            Pet.objects.filter(owner=user, is_default=True).update(is_default=False)

        new_pet = Pet.objects.create(name=pet_name, owner=user, is_default=is_default)

        return redirect("calculator:pet_detail", pk=new_pet.id)


class PetDetailView(LoginRequiredMixin, DetailView):
    model = Pet
    template_name = "calculator/pet_detail.html"

    def get_queryset(self):
        return Pet.objects.filter(owner=self.request.user)


class PetUpdateView(LoginRequiredMixin, UpdateView):
    model = Pet
    fields = ["name", "pet_icon", "is_default"]
    template_name = "calculator/pet_update.html"

    def form_valid(self, form):
        is_default = form.cleaned_data.get("is_default")
        if is_default:
            Pet.objects.filter(owner=self.request.user, is_default=True).update(is_default=False)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("calculator:pet_detail", kwargs={"pk": self.object.id})


class PetCalculatePrice(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pet_id = kwargs.get("pk")
        pet = get_object_or_404(Pet, pk=pet_id, owner=request.user)

        if request.POST.get("calculate_price") == "off":
            pet.calculate_price = "on"
        else:
            pet.calculate_price = "off"
        pet.save()

        return redirect("calculator:pet_detail", pk=pet.id)


class PetDeleteView(LoginRequiredMixin, DeleteView):
    model = Pet
    success_url = reverse_lazy("calculator:home")


class FoodCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pet_id = request.POST.get("pet_id")
        pet = get_object_or_404(Pet, pk=pet_id)
        new_food = Food.objects.create(pet=pet,)
        return render(request, "components/food_form.html", {"food": new_food, "pet": pet})


class FoodUpdateView(LoginRequiredMixin, View):
    @staticmethod
    def to_int_or_none(n) -> int | None:
        try:
            return int(n)
        except (ValueError, TypeError):
            return None

    @staticmethod
    def to_float_or_none(n) -> float | None:
        try:
            return float(n)
        except (ValueError, TypeError):
            return None

    def post(self, request, *args, **kwargs):
        food_id = kwargs.get("pk")
        food = get_object_or_404(Food, pk=food_id)

        food.name = request.POST.get("name") or None
        food.kcal = self.to_int_or_none(request.POST.get("kcal"))
        food.meals = self.to_int_or_none(request.POST.get("meals"))
        food.meal_size = self.to_int_or_none(request.POST.get("meal_size"))
        food.package_size = self.to_int_or_none(request.POST.get("package_size"))
        food.package_price = self.to_float_or_none(request.POST.get("package_price"))

        food.save()
        food.refresh_from_db()
        return render(request, "components/food_form.html", {"food": food, "pet": food.pet})


class FoodDeleteView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        food_id = kwargs.get("pk")
        food = get_object_or_404(Food, pk=food_id)
        food.delete()
        return HttpResponse("")

templates/calculator/home.html
{% extends "base.html" %}
{% load static %}

{% block body %}
<div class="container-fluid">

  <div class="row justify-content-center align-items-center">
    <div class="col-auto box">

      <div class="box-header">
        Add Pet
      </div>

      <div class="box-content box-content-margin-top">
        Add your pet to get started
      </div>

      <div class="box-btn-margin-top">
        {% include "includes/add_pet_button.html" %}
      </div>
      {% include "includes/add_pet_modal.html" %}

    </div>
  </div>
</div>
{% endblock %}

templates/calculator/home_guest.html
{% extends "base.html" %}
{% load static %}

{% block body %}

  <div class="container-fluid">

    <!-- Title and Edit Button -->
    <div class="row justify-content-center"
         style="margin: 0 10px 0 10px"
    >
      <!-- Main Title Section -->
      <div class="col-auto box-pet-menu">

        <div style="margin: 0 16px 0 16px;">
          <div class="text-center" style="font-weight: 700; font-size: 24px; margin-bottom: 16px;">
            Welcome to the Pet Food Calculator!
          </div>
          <div>
            <a href="{% url 'account_signup' %}" style="font-weight: 700; color: var(--primary-color)">
              Register
            </a> or
            <a href="{% url 'account_login' %}" style="font-weight: 700; color: var(--primary-color)">
              Log in
            </a> to add multiple pets, save their meals, and unlock more features.
            <div style="margin-top: 10px">
              It’s completely <b>FREE</b>, but if you’d like to support the project, you’re welcome
              to {% include "includes/bmc.html" %}
            </div>
          </div>
        </div>


        <div class="row justify-content-center align-items-center"
             style="margin: 20px 4px 0 4px; padding: 0 0 0 0;"
        >

          <!-- Add Food -->
          <div class="col-auto m-0 p-0">
            <button class="btn btn-pet-nav"
                    id="add-row"
                    style="border-radius: 30px 0 0 30px"
            >
              + Add food
            </button>
          </div>

          <!-- Calculate Price Button -->
          <div class="col-auto m-0 p-0">
            <button id="toggle-cost-btn" class="btn btn-pet-nav" style="border-radius: 0 30px 30px 0">
              Cost: OFF
            </button>
          </div>

        </div>
      </div>
    </div>


    <!-- This row is used to display the food rows dynamically -->
    <div class="row justify-content-center" id="food-rows"></div>


    <!-- Result Section -->
    <div class="row justify-content-center font-default mb-5">
      <div class="col-auto food-box">

        <table style="font-weight: 700; color: var(--dark-color);">
          <tr>
            <td style="padding: 6px 0">
              Total day energy:
            </td>
            <td style="padding: 6px 0">
              <span id="total-kcal" style="padding-left: 10px">
                0.00
              </span>
              <span>kcal</span>
            </td>
          </tr>
          <tr>
            <td>
              <span class="cost-field">
                Total day cost:
              </span>
            </td>
            <td>
              <span class="cost-field" id="total-cost" style="padding-left: 10px">
                0.00
              </span>
              <span class="cost-field">$</span>
            </td>
          </tr>
        </table>

      </div>
    </div>


    <!-- Template for a single food row -->
    <template id="food-row-template">
      <div class="col-auto food-box food-row">

        <!-- Delete Row -->
        <div class="row align-items-center justify-content-between">
          <div class="col-auto">
            <div class="row align-items-center justify-content-start m-0 p-0 gap-2">
              <div class="col-auto m-0 p-0">
                <img src="{% static 'images/pet_food_icon.png' %}"
                     alt="pet food icon"
                     style="width: 30px; height: 30px;"
                >
              </div>
              <div class="col-auto m-0 p-0">
              <span class="food-form-title">
                Food
              </span>
              </div>
            </div>
          </div>

          <div class="col-auto align-self-start">
            <button type="submit" class="btn p-0 m-0 btn-close-custom delete-row">
              <img src="{% static 'images/x-lg.svg' %}" alt="delete icon" class="d-block"/>
            </button>
          </div>
        </div>


        <div class="food-form-row">
          <label class="food-form-label">Food kcal/kg</label>
          <input name="kcal"
                 autocomplete="off"
                 class="form-control form-control-sm food-form-field kcalPerKg"
                 placeholder="kcal/kg"
                 aria-label="Kcal per kg"/>
        </div>


        <div class="food-form-row">
          <label class="food-form-label">Meals per day</label>
          <input name="meals"
                 autocomplete="off"
                 class="form-control form-control-sm food-form-field mealsNumber"
                 placeholder="meals"
                 aria-label="Meals per day"/>
        </div>


        <div class="food-form-row">
          <label class="food-form-label">Meal size</label>
          <input name="meal_size"
                 autocomplete="off"
                 class="form-control form-control-sm food-form-field portionSize"
                 placeholder="grams"
                 aria-label="Meal size"/>
        </div>


        <div class="food-form-row cost-field">
          <label class="food-form-label">Package size</label>
          <input name="package_size"
                 autocomplete="off"
                 class="form-control form-control-sm food-form-field packageSize"
                 placeholder="grams"
                 aria-label="Package size"/>
        </div>


        <div class="food-form-row cost-field">
          <label class="food-form-label">Package price</label>
          <input name="package_price"
                 autocomplete="off"
                 class="form-control form-control-sm food-form-field price"
                 placeholder="$"
                 aria-label="Package price"/>
        </div>


        <!-- Results -->
        <div class="row">
          <div class="col"
               style="padding: 10px 0 0 0; margin: 10px 10px 0 10px; border-top: 1px solid #d4d5da;"
          >
            <div>
              <table>
                <tr>
                  <td>Day energy:</td>
                  <td>
                  <span class="kcal-output" style="margin-left: 8px">
                    0.00
                  </span>
                    <span>kcal</span>
                  </td>
                </tr>
                <tr>
                  <td><span class="cost-field">Day cost:</span></td>
                  <td>
                  <span class="cost-output cost-field" style="margin-left: 8px">
                    0.00
                  </span>
                    <span class="cost-field">$</span>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>

      </div>
    </template>


    <script src="/static/js/home_guest_script.js"></script>

  </div>
{% endblock %}

templates/calculator/pet_confirm_delete.html
{% extends "base.html" %}

{% block body %}

<div class="container-fluid">
  <div class="row justify-content-center align-items-center">
    <div class="col-auto box">

      <div class="box-header text-center">
        Delete Pet
      </div>

      <div class="box-content box-content-margin-top">
        Are you sure you want to delete {{ object.name }}?
      </div>

      <form method="post">
        {% csrf_token %}
        <div>
          <button type="submit" class="btn btn-dark w-100 box-btn-margin-top">Yes, delete</button>
        </div>
        <div>
          <a href="{% url 'calculator:pet_update' pk=object.id %}"
             class="btn btn-cancel w-100"
             style="margin-top: 28px;"
          >
            No, go back
          </a>
        </div>
      </form>

    </div>
  </div>
</div>

{% endblock %}

templates/calculator/pet_detail.html
{% extends "base.html" %}
{% load static %}

{% block body %}
  <div class="container-fluid">

    <!-- Title and Edit Button -->
    <div class="row justify-content-center">
      <!-- Main Title Section -->
      <div class="col-auto box-pet-menu">

        <div class="row justify-content-center align-items-center px-3">
          <!-- Pet Icon + Name -->
          <div class="col-auto p-0">
            <img src="{% static 'images/pets/' %}{{ pet.pet_icon }}"
                 alt="pet icon"
                 style="width: 40px; height: 40px;"
            >
          </div>
          <div class="col-auto p-0" style="margin-left: 10px;">
          <span class="box-header"
          >
            {{ pet.name | title }}
          </span>
          </div>
        </div>

        <div class="row justify-content-center align-items-center"
             style="margin: 10px 4px 0 4px; padding: 0 0 0 0;"
        >

          <!-- Add Food -->
          <div class="col-auto m-0 p-0">
            <form hx-post="{% url 'calculator:food_create' %}"
                  hx-target="#food-list"
                  hx-swap="beforeend">
              {% csrf_token %}
              <input type="hidden" name="pet_id" value="{{ pet.id }}">
              <button class="btn btn-pet-nav"
                      type="submit"
                      style="border-radius: 30px 0 0 30px"
              >
                + Add food
              </button>
            </form>
          </div>

          <!-- Edit Pet -->
          <div class="col-auto m-0 p-0">
            <a href="{% url 'calculator:pet_update' pk=pet.id %}"
               class="btn btn-pet-nav"
               style="border-radius: 0 0 0 0"
            >
              Edit
            </a>
          </div>

          <!-- Calculate Price Button -->
          <div class="col-auto m-0 p-0">
            <form action="{% url 'calculator:calculate_price' pk=pet.id %}"
                  method="post"
            >
              {% csrf_token %}
              <input type="hidden" name="calculate_price" value="{{ pet.calculate_price }}">
              <button class="btn btn-pet-nav"
                      type="submit"
                      style="border-radius: 0 30px 30px 0"
              >
                Cost: {{ pet.calculate_price | upper }}
              </button>
            </form>
          </div>

        </div>
      </div>
    </div>

    <!-- Food List -->
    <div class="row justify-content-center font-default" id="food-list">
      {% for food in pet.foods.all %}
        {% include "components/food_form.html" %}
      {% endfor %}
    </div>

    <!-- Result Section -->
    <div class="row justify-content-center font-default mb-5">
      <div class="col-auto food-box">

        <table style="font-weight: 700; margin-bottom: 20px; color: var(--dark-color);">
          <tr>
            <td style="padding: 6px 0">Total day energy:</td>
            <td style="padding: 6px 0"><span id="total-kcal" style="padding-left: 10px">0</span></td>
          </tr>
          <tr {% if pet.calculate_price == 'off' %} hidden {% endif %}>
            <td>Total day cost:</td>
            <td><span id="total-cost" style="padding-left: 10px">0.00</span></td>
          </tr>
        </table>

        <!-- Calculate Button -->
        <button class="btn btn-primary w-100" type="button" id="calculate">Calculate</button>

      </div>
    </div>

    <!-- Total Calculation Script -->
    <script>
        const userCurrency = "{{ user.currency }}";
    </script>
    <script src="/static/js/pet_detail_total_calculation.js"></script>

  </div>
{% endblock %}

templates/calculator/pet_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}


{% block body %}
  <div class="container-fluid">

    <div class="row justify-content-center align-items-center">
      <div class="col-auto box">

        <div class="row justify-content-center align-items-center px-2 pb-2">
          <!-- Pet Icon + Name -->
          <div class="col-auto p-0">
            <img src="{% static 'images/pets/' %}{{ pet.pet_icon }}"
                 alt="pet icon"
                 style="width: 40px; height: 40px;"
            >
          </div>
          <div class="col-auto p-0" style="margin-left: 10px;">
          <span class="box-header"
          >
            {{ pet.name | title }}
          </span>
          </div>
        </div>

        <form method="post" class="box-content box-content-margin-top">
          {% csrf_token %}
          {{ form | crispy }}
          <input type="submit"
                 value="Update"
                 class="btn btn-primary w-100 box-btn-under-form-margin-top"
          >
        </form>

        <a href="{% url 'calculator:pet_detail' pet.pk %}"
           class="btn btn-cancel w-100"
           style="margin-top: 10px;"
        >
          Cancel
        </a>

        <a href="{% url 'calculator:pet_delete' pet.pk %}"
           class="btn btn-dark w-100"
           style="margin-top: 46px;"
        >
          Delete
        </a>

      </div>
    </div>

  </div>
{% endblock %}