PetFoodCalculator/urls.py
from django.contrib import admin
from django.urls import path, include

from PetFoodCalculator import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("calculator.urls", namespace="calculator")),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

calculator/urls.py
from django.urls import path
from calculator import views

app_name = "calculator"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("pet/create/", views.PetCreateView.as_view(), name="pet_create"),
    path("pet/<uuid:pk>/", views.PetDetailView.as_view(), name="pet_detail"),
    path("pet/<uuid:pk>/update/", views.PetUpdateView.as_view(), name="pet_update"),
    path("pet/<uuid:pk>/delete/", views.PetDeleteView.as_view(), name="pet_delete"),
    path("pet/<uuid:pk>/calculate_price/", views.PetCalculatePrice.as_view(), name="calculate_price"),
    path("food/create/", views.FoodCreateView.as_view(), name="food_create"),
    path("food/<int:pk>/update/", views.FoodUpdateView.as_view(), name="food_update"),
    path("food/<int:pk>/delete/", views.FoodDeleteView.as_view(), name="food_delete"),
]

users/urls.py
from django.urls import path

from .views import (
    UserDetailView,
    UserSettingsView, UserDeleteView, BuyMeCoffeeView, SendMessageView,
)

app_name = "users"

urlpatterns = [
    path("me/", UserDetailView.as_view(), name="user-detail"),
    path("me/settings/", UserSettingsView.as_view(), name="user-settings"),
    path("me/delete/", UserDeleteView.as_view(), name="user-delete"),
    path("bymeacoffee/", BuyMeCoffeeView.as_view(), name="by-me-a-coffee"),
    path("send-message", SendMessageView.as_view(), name="send-message"),
]

templates/includes/add_pet_button.html
<button type="button"
        class="btn btn-primary w-100"
        data-bs-toggle="modal"
        data-bs-target="#petModal"
>
  Add Pet
</button>

templates/includes/add_pet_modal.html
<!-- Modal Add Pet -->
<div class="modal fade"
     id="petModal"
     tabindex="-1"
     aria-labelledby="newPetModalLabel"
     aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content box">

      <div class="modal-header border-0 m-0 p-0">
        <span class="box-header">Add Pet</span>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body box-content box-content-margin-top m-0 p-0">
        <form method="POST" action="{% url 'calculator:pet_create' %}">
          {% csrf_token %}
          <label class="form-label" for="pet_name">Pet Name</label>
          <input class="form-control"
                 id="pet_name"
                 type="text"
                 name="pet_name"
                 maxlength="30"
                 required
          >
          <div class="form-check" style="margin-top: 24px;">
            <input class="form-check-input"
                   type="checkbox"
                   value="on"
                   id="is_default"
                   name="is_default"
            >
            <label class="form-check-label" for="is_default">
              Default
            </label>
          </div>
          <div>
            <input class="btn btn-primary box-btn-margin-top w-100" type="submit" value="Save">
          </div>
        </form>
      </div>

    </div>
  </div>
</div>

templates/includes/bmc.html
{% load static %}

<a href="{% url "users:by-me-a-coffee" %}">
  <img src="{% static 'images/bmc.svg' %}"
       alt="Buy Me a Coffee"
       style="width: 140px; border-radius: 60px"
  />
</a>

templates/includes/food_card.html
<div class="col-auto m-3 bg-white rounded-5 food-row box-shadow" id="food-card-{{ food.id }}">

  <!-- Delete Food -->
  <div class="row align-items-center justify-content-between px-3" style="margin-top: 18px; margin-bottom: 14px;">
    <div class="col-auto">
      <i class="bi bi-fork-knife"></i>
    </div>
    <form method="post" action="{% url 'calculator:food_delete' %}" class="col-auto">
      {% csrf_token %}
      <input type="hidden" name="pet_id" value="{{ pet.id }}">
      <input type="hidden" name="food_id" value="{{ food.id }}">
      <button type="submit" class="btn p-0 text-decoration-none delete-row text-secondary align-self-end mb-3">
        <span style="color: var(--primary-color);">
          <i class="bi bi-x-lg"></i>
        </span>
      </button>
    </form>
  </div>

  <!-- Food Form -->
  <form
    hx-post="{% url 'calculator:food_update' food_id=food.id %}"
    hx-trigger="change"
    hx-target="#food-card-{{ food.id }}"
    hx-swap="outerHTML"
  >

    {% csrf_token %}
    <input type="hidden" name="pet_id" value="{{ pet.id }}" />
    <input type="hidden" name="food_id" value="{{ food.id }}" />

    <div class="d-flex align-items-center gap-2 px-3">
      <label class="food-form-label">Food</label>
      <input name="food_name"
             autocomplete="off"
             class="form-control form-control-sm food-form-field"
             placeholder="name"
             value="{{ food.name }}" aria-label="Food name" />
    </div>

    <div class="d-flex align-items-center gap-2 mt-2 px-3">
      <label class="food-form-label">Food kcal/kg</label>
      <input name="kcal"
             autocomplete="off"
             class="form-control form-control-sm food-form-field"
             placeholder="kcal/kg"
             value="{{ food.kcal }}"
             aria-label="Kcal per kg" />
    </div>

    <div class="d-flex align-items-center gap-2 mt-2 px-3">
      <label class="food-form-label">Meals per day</label>
      <input name="meals"
             autocomplete="off"
             class="form-control form-control-sm food-form-field mealsNumber"
             placeholder="meals"
             value="{{ food.meals }}"
             aria-label="Meals per day" />
    </div>

    <div class="d-flex align-items-center gap-2 mt-2 px-3">
      <label class="food-form-label">Meal size</label>
      <input name="meal_size"
             autocomplete="off"
             class="form-control form-control-sm food-form-field portionSize"
             placeholder="grams"
             value="{{ food.meal_size }}"
             aria-label="Meal size" />
    </div>

    <div class="d-flex align-items-center gap-2 mt-2 px-3 cost-field">
      <label class="food-form-label">Package size</label>
      <input name="package_size"
             autocomplete="off"
             class="form-control form-control-sm food-form-field packageSize"
             placeholder="grams"
             value="{{ food.package_size }}"
             aria-label="Package size" />
    </div>

    <div class="d-flex align-items-center gap-2 mt-2 px-3 cost-field">
      <label class="food-form-label">Package price</label>
      <input name="package_price"
             autocomplete="off"
             class="form-control form-control-sm food-form-field price"
             placeholder="$" value="{{ food.package_price }}"
             aria-label="Package price" />
    </div>
  </form>

  <!-- Results -->
  <div class="row" style="margin-top: 20px;">
    <div class="col" style="padding-top: 20px; padding-bottom: 20px; font-weight: 700; border-top: 1px solid #8ea6fe;">
      <div class="px-3">
        <strong>Kcal per day:</strong> <span class="kcal-output">{{ food.kcal_per_day }}</span>
      </div>
      <div class="cost-field px-3">
        <strong>Cost per day:</strong> <span class="cost-output">{{ food.cost_per_day }}</span>
      </div>
    </div>
  </div>

</div>

templates/includes/food_form.html
<div class="col-auto m-3 bg-white rounded-5 box-shadow" id="food-card-{{ food.id }}">

  <!-- Delete Food -->
  <div class="row align-items-center justify-content-between px-3" style="margin-top: 18px; margin-bottom: 14px;">
    <div class="col-auto">
      <i class="bi bi-fork-knife"></i>
    </div>

    <form class="col-auto"
          hx-post="{% url 'calculator:food_delete' food.id %}"
          hx-target="#food-card-{{ food.id }}"
          hx-swap="outerHTML"
    >
      {% csrf_token %}
      <button type="submit" class="btn p-0 text-decoration-none text-secondary align-self-end">
        <span style="color: var(--primary-color);">
          <i class="bi bi-x-lg"></i>
        </span>
      </button>
    </form>
  </div>

  <!-- Food Form -->
  <form hx-post="{% url 'calculator:food_update' food.id %}"
        hx-target="#food-card-{{ food.id }}"
        hx-swap="outerHTML"
        hx-trigger="click from:#calculate"
  >
    {% csrf_token %}
    <input type="hidden" name="pet_id" value="{{ pet.id }}" />
    <input type="hidden" name="food_id" value="{{ food.id }}" />

    <div class="d-flex align-items-center gap-2 px-3">
      <label class="food-form-label">Food name</label>
      <input name="name"
             autocomplete="off"
             class="form-control form-control-sm food-form-field input"
             placeholder="name"
             value="{% if food.name %}{{ food.name }}{% endif %}"
             aria-label="Food name"
      />
    </div>

    <div class="d-flex align-items-center gap-2 mt-2 px-3">
      <label class="food-form-label">Food kcal/kg</label>
      <input name="kcal"
             autocomplete="off"
             class="form-control form-control-sm food-form-field input"
             placeholder="kcal/kg"
             value="{% if food.kcal %}{{ food.kcal }}{% endif %}"
             aria-label="Kcal per kg" />
    </div>

    <div class="d-flex align-items-center gap-2 mt-2 px-3">
      <label class="food-form-label">Meals per day</label>
      <input name="meals"
             autocomplete="off"
             class="form-control form-control-sm food-form-field input"
             placeholder="meals"
             value="{% if food.meals %}{{ food.meals }}{% endif %}"
             aria-label="Meals per day" />
    </div>

    <div class="d-flex align-items-center gap-2 mt-2 px-3">
      <label class="food-form-label">Meal size</label>
      <input name="meal_size"
             autocomplete="off"
             class="form-control form-control-sm food-form-field input"
             placeholder="grams"
             value="{% if food.meal_size %}{{ food.meal_size }}{% endif %}"
             aria-label="Meal size" />
    </div>

    {% if pet.calculate_price == 'on' %}
      <div class="d-flex align-items-center gap-2 mt-2 px-3 cost-field">
        <label class="food-form-label">Package size</label>
        <input name="package_size"
               autocomplete="off"
               class="form-control form-control-sm food-form-field input"
               placeholder="grams"
               value="{% if food.package_size %}{{ food.package_size }}{% endif %}"
               aria-label="Package size" />
      </div>

      <div class="d-flex align-items-center gap-2 mt-2 px-3 cost-field">
        <label class="food-form-label">Package price</label>
        <input name="package_price"
               autocomplete="off"
               class="form-control form-control-sm food-form-field input"
               placeholder="{{ user.currency }}" value="{% if food.package_price %}{{ food.package_price }}{% endif %}"
               aria-label="Package price" />
      </div>
    {% endif %}
  </form>

  <!-- Results -->
  <div class="row" style="margin-top: 20px;">
    <div class="col" style="padding-top: 10px; padding-bottom: 14px; font-weight: 700; border-top: 1px solid #8ea6fe;">
      <div class="px-3">
        <table>
          <tr>
            <td>Day energy:</td>
            <td>
              <span class="kcal-per-day" style="margin-left: 20px;">
                {% if food.kcal_per_day %}{{ food.kcal_per_day }}{% else %}0.00{% endif %} kcal
              </span>
            </td>
          </tr>
          <tr {% if pet.calculate_price == 'off' %} hidden {% endif %}>
            <td>Day cost:</td>
            <td>
              <span class="cost-per-day" style="margin-left: 20px;">
                {% if food.cost_per_day %}{{ food.cost_per_day }}{% else %}0.00{% endif %} {{ user.currency }}
              </span>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>

</div>

templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-dark navbar-expand-lg" style="background-color: var(--primary-color);">
  <div class="container-fluid">
    <a class="navbar-brand ms-lg-4"
       style="color: #ffffff; font-size: 30px; font-weight: 900;"
       href={% url "calculator:home" %}
    >
      <img src="{% static 'images/app_logo.png' %}"
           alt="Pet Food Calculator Logo"
           style="width: 32px; height: 32px;"
      /> Pet Food Calculator
    </a>
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'account_login' %}">Log in</a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'account_signup' %}">Register</a>
          </li>
        {% endif %}

        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'users:user-detail' %}">Profile</a>
          </li>

          <!-- Pets Dropdown Menu -->
          <li class="nav-item dropdown">

            <a class="nav-link dropdown-toggle"
               href="#"
               role="button"
               data-bs-toggle="dropdown"
               aria-expanded="false"
            >
              Your Pets
            </a>

            <div class="dropdown-menu shadow" style="padding: 20px; border-radius: 20px; border: none;">
              {% for pet in user.pets.all %}
                <div>

                  <a class="dropdown-link-custom d-block" href="{% url 'calculator:pet_detail' pk=pet.id %}">
                    <div class="row justify-content-start align-items-center flex-nowrap">
                      <div class="col-auto m-0 p-0">
                        <img src="{% static 'images/pets/' %}{{ pet.pet_icon }}"
                             alt="pet icon"
                             style="width: 26px; height: 26px; margin-right: 10px;"
                        >
                      </div>

                      <div class="col-auto m-0 p-0">
                        {{ pet.name | title }}
                      </div>

                      <div class="col-auto m-0 p-0">
                        {% if pet.is_default %}
                          <span style="font-weight: 400; opacity: 0.5; margin-left: 6px;">
                        (Default)
                      </span>
                        {% endif %}
                      </div>
                    </div>
                  </a>
                </div>
              {% endfor %}

              <!-- Add Pet Button -->
              <div style="margin-top: 20px;">
                {% include "includes/add_pet_button.html" %}
              </div>

            </div>
          </li>
        {% endif %}
      </ul>

      <div class="nav-item me-5 my-3 my-lg-0">
        <a class="nav-link text-white" href="{% url 'users:send-message' %}">Contact me</a>
      </div>

      {% if user.is_authenticated %}
        <div class="me-4 my-3 my-lg-0">
          {% include "includes/bmc.html" %}
        </div>
      {% endif %}

    </div>
  </div>
</nav>

<!-- Add Pet Modal -->
{% include "includes/add_pet_modal.html" %}

templates/includes/user_cancel_btn.html
<div>
  <a href="{% url 'users:user-detail' %}"
     class="btn btn-cancel w-100"
  >
    Cancel
  </a>
</div>