PetFoodCalculator/urls.py
from django.contrib import admin
from django.urls import path, include

from PetFoodCalculator import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("calculator.urls", namespace="calculator")),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

users/urls.py
from django.urls import path

from .views import (
    UserDetailView,
    UserSettingsView, UserDeleteView, BuyMeCoffeeView, SendMessageView,
)

app_name = "users"

urlpatterns = [
    path("me/", UserDetailView.as_view(), name="user-detail"),
    path("me/settings/", UserSettingsView.as_view(), name="user-settings"),
    path("me/delete/", UserDeleteView.as_view(), name="user-delete"),
    path("bymeacoffee/", BuyMeCoffeeView.as_view(), name="by-me-a-coffee"),
    path("send-message", SendMessageView.as_view(), name="send-message"),
]

users/models.py
import uuid

from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from calculator.helpers import tm_new_user_created


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)

    UNIT_CHOICES = [("g", "Grams"), ("lb", "Pounds")]

    CURRENCY_CHOICES = [
        ("$", "US Dollar"),
        ("€", "Euro"),
        ("£", "British Pound"),
        ("¥", "Japanese Yen"),
        ("₴", "Ukrainian Hryvnia"),
        ("₹", "Indian Rupee"),
        ("₺", "Turkish Lira"),
        ("₩", "South Korean Won"),
        ("C$", "Canadian Dollar"),
        ("A$", "Australian Dollar"),
        ("CHF", "Swiss Franc"),
        ("NZ$", "New Zealand Dollar"),
        ("SEK", "Swedish Krona"),
        ("NOK", "Norwegian Krone"),
        ("DKK", "Danish Krone"),
        ("SGD", "Singapore Dollar"),
        ("HK$", "Hong Kong Dollar"),
        ("MX$", "Mexican Peso"),
        ("BRL", "Brazilian Real"),
    ]

    weight_unit = models.CharField(
        max_length=2, choices=UNIT_CHOICES, default="g"
    )
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default="$")
    has_visited_buy_me_coffee = models.BooleanField(default=False)


@receiver(post_save, sender=get_user_model())
def new_user_created_telegram_notification(sender, instance, created, **kwargs):
    if created:
        tm_new_user_created(instance.date_joined, instance.email)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model


class UserSettingsForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = [
            "currency",
        ]


class MessageForm(forms.Form):
    email = forms.EmailField(
        required=False,
        widget=forms.EmailInput(attrs={"placeholder": "Your email (optional)"}),
    )
    message = forms.CharField(label="Message", max_length=1000, widget=forms.Textarea)


from allauth.account.forms import LoginForm


class CustomLoginForm(LoginForm):
    """Custom login form to remove 'Forgot your password?'."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if "password" in self.fields:
            self.fields["password"].help_text = None

users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic

from PetFoodCalculator import settings
from calculator.helpers import (
    tm_user_visited_bmc_first_time,
    tm_user_visited_bmc_again,
    tm_guest_visited_bmc_first_time,
    tm_send_message,
)
from users.forms import UserSettingsForm, MessageForm


class UserDetailView(LoginRequiredMixin, generic.TemplateView):
    template_name = "users/user_detail.html"


class UserSettingsView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = UserSettingsForm
    template_name = "users/user_settings.html"
    success_url = reverse_lazy("users:user-detail")

    def get_object(self, queryset=None):
        return self.request.user


class UserDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = get_user_model()
    success_url = reverse_lazy("calculator:home")

    def get_object(self, queryset=None):
        return self.request.user


class BuyMeCoffeeView(generic.View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated and not request.user.has_visited_buy_me_coffee:
            request.user.has_visited_buy_me_coffee = True
            request.user.save(update_fields=["has_visited_buy_me_coffee"])
            tm_user_visited_bmc_first_time.delay(request.user.email)
        elif request.user.is_authenticated and request.user.has_visited_buy_me_coffee:
            tm_user_visited_bmc_again.delay(request.user.email)
        else:
            tm_guest_visited_bmc_first_time.delay()
        return redirect(getattr(settings, "BUY_ME_A_COFFEE_LINK"))


class SendMessageView(generic.View):
    def get(self, request, *args, **kwargs):
        form = MessageForm()
        return render(request, "users/send_message.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = MessageForm(request.POST)
        if form.is_valid():
            tm_send_message.delay(
                message=form.cleaned_data.get("message", ""),
                email=form.cleaned_data.get("email", ""),
            )
            messages.success(request, "Thank you! Your message has been sent.")
            return redirect("users:send-message")
        else:
            return redirect("users:send-message")

templates/users/send_message.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}

{% block body %}


  <div class="container-fluid">

    <div class="row justify-content-center align-items-center">
      <div class="col-11 col-sm-9 col-md-7 col-lg-5 col-xl-4 box">

        <div class="row justify-content-center align-items-center ">
          <div class="col-auto p-0">
            <img src="{% static 'images/send_message_icon.png' %}"
                 alt="pet icon"
                 style="width: 40px; height: 40px;"
            >
          </div>
          <div class="col-auto p-0" style="margin-left: 10px;">
          <span class="box-header"
          >
            Contact Me
          </span>
          </div>
        </div>

        <div style="margin: 10px 0 10px 0">
          Have questions, suggestions, or feedback? Send me a message through this form, and I’ll get back to you as
          soon as possible!
        </div>

        <div class="box-content">
          <form method="POST" action="{% url 'users:send-message' %}">
            {% csrf_token %}

            <!-- Email Input -->
            {% if not user.is_authenticated %}
              <label class="form-label box-content-margin-top" for="email">Email</label>
              <input class="form-control"
                     id="email"
                     type="email"
                     name="email"
                     placeholder="Your email (optional)"
              >
            {% else %}
              <input type="email" name="email" value="{{ user.email }}" hidden aria-label="Email">
            {% endif %}

            <!-- Message Input -->
            <label class="form-label box-content-margin-top" for="message">Message</label>
            <textarea class="form-control"
                      id="message"
                      type="text"
                      rows="6"
                      name="message"
                      maxlength="1000"
                      required
            ></textarea>

            <div>
              <input class="btn btn-primary box-btn-margin-top w-100" type="submit" value="Send">
            </div>
          </form>
        </div>
      </div>
    </div>

  </div>

{% endblock %}

templates/users/user_confirm_delete.html
{% extends "base.html" %}

{% block body %}

<div class="container-fluid">
  <div class="row justify-content-center align-items-center">
    <div class="col-auto box">

      <div class="box-header text-center">
        Delete Account
      </div>

      <div class="box-content box-content-margin-top">
        Are you sure you want to delete your account?
      </div>

      <form method="post">
        {% csrf_token %}
        <div>
          <button type="submit" class="btn btn-dark w-100 box-btn-margin-top">Yes, delete</button>
        </div>
        <div>
          <a href="{% url 'users:user-detail' %}"
             class="btn btn-cancel w-100"
             style="margin-top: 28px;"
          >
            No, go back
          </a>
        </div>
      </form>

    </div>
  </div>
</div>

{% endblock %}

templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block body %}

  <div class="container-fluid">

    <div class="row justify-content-center align-items-center">
      <div class="col-auto box">

        <div class="row justify-content-center align-items-center">
          <div class="col-auto p-0">
            <img src="{% static 'images/user_profile_icon.png' %}"
                 alt="pet icon"
                 style="width: 32px; height: 32px;"
            >
          </div>
          <div class="col-auto p-0" style="margin-left: 10px;">
          <span class="box-header"
          >
            Profile
          </span>
          </div>
        </div>

        <div class="box-content box-content-margin-top">
          <span>Email:</span> {{ user.email }}
        </div>
        <div class="box-content" style="margin: 6px 0;">
          <span>Currency:</span> {{ user.currency }}
        </div>

        <div class="box-btn-margin-top">
          <a class="btn btn-primary w-100" href="{% url 'users:user-settings' %}">Settings</a>
        </div>

        <div style="margin: 20px 0;">
          <a class="btn btn-primary w-100" href="{% url 'account_change_password' %}">Change Password</a>
        </div>

        <div style="margin: 20px 0;">
          <a class="btn btn-primary w-100" href="{% url 'account_logout' %}">Logout</a>
        </div>

        <div style="margin-top: 46px;">
          <a class="btn btn-dark w-100" href="{% url 'users:user-delete' %}">Delete</a>
        </div>

      </div>
    </div>

  </div>

{% endblock %}

templates/users/user_settings.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}


{% block body %}

<div class="container-fluid">

  <div class="row justify-content-center align-items-center">
    <div class="col-auto box">

      <div class="box-header text-center">
        Settings
      </div>

      <form method="post" class="box-content box-content-margin-top">
        {% csrf_token %}
        {{ form | crispy }}

          <button type="submit" class="btn btn-primary box-btn-under-form-margin-top w-100">
            Update
          </button>
      </form>

      <div style="margin-top: 20px;">
        {% include "includes/user_cancel_btn.html" %}
      </div>

    </div>
  </div>

</div>
{% endblock %}